/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// biblioteci de importat
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JButton;

// clasa meniu principal
public class MeniuPrincipal extends javax.swing.JFrame {
    
    private javax.swing.JPanel ContainerPrincipal; // container principal pentru lucrul cu mai multe panel-uri
    private java.awt.CardLayout cardLayout; // lucrul cu mai multe panel-uri
    
    private List<File> fisiereSelectate = new ArrayList<>(); // array list în care salvez fișierele selectate
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MeniuPrincipal.class.getName());
    
    // funcția care îmi găsește executabilele
    private String gasesteExecutabil(String numeWindows, String numeUnix) {
        // nume os
        String os = System.getProperty("os.name").toLowerCase();
        String nume;

        if (os.contains("win")) {
            nume = numeWindows; // CompresorHuffman.exe
        } else if (os.contains("mac")) {
            nume = numeUnix + "_mac"; // CompresorHuffman_mac
        } else {
            nume = numeUnix + "_linux"; // CompresorHuffman_linux
        }

        // caut in folderul executabile langa .jar
        String cale = System.getProperty("user.dir") + File.separator + "executabile" + File.separator + nume;
        if (new File(cale).exists()) return cale;

        // caut langa .class in timpul dezvoltarii in NetBeans
        String caleNetBeans = System.getProperty("user.dir") + File.separator + "build"
                            + File.separator + "classes"
                            + File.separator + "executabile"
                            + File.separator + nume;
        if (new File(caleNetBeans).exists()) return caleNetBeans;

        return null;
    }
    
    // constructor
    public MeniuPrincipal() {
        initComponents();
        setTitle("Compresor de fișiere"); // setez numele ferestrei

        cardLayout = new java.awt.CardLayout();
        ContainerPrincipal = new javax.swing.JPanel(cardLayout);
        
        // adaug meniul principal și ecranele de compresare/decompresare
        ContainerPrincipal.add(PanelMeniuPrincipal, "meniu"); 
        ContainerPrincipal.add(PanelCompresare, "compresare");
        ContainerPrincipal.add(PanelDecompresare, "decompresare");

        setContentPane(ContainerPrincipal);
        
        // reafișez corect panel-ul curent
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButonCompresie = new javax.swing.JButton();
        ButonDecompresie = new javax.swing.JButton();
        PanelCompresare = new javax.swing.JPanel();
        ButonInapoi1 = new javax.swing.JButton();
        ButonCompresare = new javax.swing.JButton();
        LabelAlegereCompresare = new javax.swing.JLabel();
        ButonAlegeFisiereCompresare = new javax.swing.JButton();
        ButonAnulareSelectareFisiere1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaFisiereCompresare = new javax.swing.JList<>();
        PanelDecompresare = new javax.swing.JPanel();
        ButonInapoi2 = new javax.swing.JButton();
        ButonDecompresare = new javax.swing.JButton();
        LabelAlegereDecompresare = new javax.swing.JLabel();
        ButonAlegeFisiereDecompresare = new javax.swing.JButton();
        ButonAnulareSelectareFisiere2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaFisiereDecompresare = new javax.swing.JList<>();
        PanelMeniuPrincipal = new javax.swing.JPanel();
        ButonAlegereCompresare = new javax.swing.JButton();
        ButonAlegereDecompresare = new javax.swing.JButton();
        LabelTitlu = new javax.swing.JLabel();

        ButonCompresie.setText("Compresie");

        ButonDecompresie.setText("Decompresie");

        PanelCompresare.setBackground(new java.awt.Color(255, 255, 102));
        PanelCompresare.setForeground(new java.awt.Color(0, 0, 0));
        PanelCompresare.setPreferredSize(new java.awt.Dimension(400, 300));

        ButonInapoi1.setText("Înapoi");
        ButonInapoi1.addActionListener(this::ButonInapoi1ActionPerformed);

        ButonCompresare.setText("Compresare");
        ButonCompresare.addActionListener(this::ButonCompresareActionPerformed);

        LabelAlegereCompresare.setBackground(new java.awt.Color(255, 255, 0));
        LabelAlegereCompresare.setForeground(new java.awt.Color(0, 0, 0));
        LabelAlegereCompresare.setText("Alege fișierele:");

        ButonAlegeFisiereCompresare.setText("Alege");
        ButonAlegeFisiereCompresare.addActionListener(this::ButonAlegeFisiereCompresareActionPerformed);

        ButonAnulareSelectareFisiere1.setText("Anuleaza selectare");
        ButonAnulareSelectareFisiere1.addActionListener(this::ButonAnulareSelectareFisiere1ActionPerformed);

        jScrollPane1.setViewportView(ListaFisiereCompresare);

        javax.swing.GroupLayout PanelCompresareLayout = new javax.swing.GroupLayout(PanelCompresare);
        PanelCompresare.setLayout(PanelCompresareLayout);
        PanelCompresareLayout.setHorizontalGroup(
            PanelCompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompresareLayout.createSequentialGroup()
                .addGroup(PanelCompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompresareLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButonInapoi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButonCompresare))
                    .addGroup(PanelCompresareLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LabelAlegereCompresare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButonAlegeFisiereCompresare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(ButonAnulareSelectareFisiere1))
                    .addGroup(PanelCompresareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        PanelCompresareLayout.setVerticalGroup(
            PanelCompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCompresareLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelCompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAlegereCompresare, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonAlegeFisiereCompresare)
                    .addComponent(ButonAnulareSelectareFisiere1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonInapoi1)
                    .addComponent(ButonCompresare))
                .addContainerGap())
        );

        PanelDecompresare.setBackground(new java.awt.Color(102, 255, 102));
        PanelDecompresare.setForeground(new java.awt.Color(0, 0, 0));
        PanelDecompresare.setPreferredSize(new java.awt.Dimension(400, 300));

        ButonInapoi2.setText("Înapoi");
        ButonInapoi2.addActionListener(this::ButonInapoi2ActionPerformed);

        ButonDecompresare.setText("Decompresare");
        ButonDecompresare.addActionListener(this::ButonDecompresareActionPerformed);

        LabelAlegereDecompresare.setBackground(new java.awt.Color(255, 255, 0));
        LabelAlegereDecompresare.setForeground(new java.awt.Color(0, 0, 0));
        LabelAlegereDecompresare.setText("Alege fișierele:");

        ButonAlegeFisiereDecompresare.setText("Alege");
        ButonAlegeFisiereDecompresare.addActionListener(this::ButonAlegeFisiereDecompresareActionPerformed);

        ButonAnulareSelectareFisiere2.setText("Anuleaza selectare");
        ButonAnulareSelectareFisiere2.addActionListener(this::ButonAnulareSelectareFisiere2ActionPerformed);

        jScrollPane2.setViewportView(ListaFisiereDecompresare);

        javax.swing.GroupLayout PanelDecompresareLayout = new javax.swing.GroupLayout(PanelDecompresare);
        PanelDecompresare.setLayout(PanelDecompresareLayout);
        PanelDecompresareLayout.setHorizontalGroup(
            PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDecompresareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDecompresareLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButonInapoi2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButonDecompresare))
                    .addGroup(PanelDecompresareLayout.createSequentialGroup()
                        .addComponent(LabelAlegereDecompresare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButonAlegeFisiereDecompresare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(ButonAnulareSelectareFisiere2)))
                .addContainerGap())
            .addGroup(PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDecompresareLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jScrollPane2)
                    .addGap(6, 6, 6)))
        );
        PanelDecompresareLayout.setVerticalGroup(
            PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDecompresareLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAlegereDecompresare, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButonAlegeFisiereDecompresare)
                    .addComponent(ButonAnulareSelectareFisiere2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonInapoi2)
                    .addComponent(ButonDecompresare))
                .addContainerGap())
            .addGroup(PanelDecompresareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDecompresareLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelMeniuPrincipal.setBackground(new java.awt.Color(102, 204, 255));
        PanelMeniuPrincipal.setForeground(new java.awt.Color(0, 0, 0));

        ButonAlegereCompresare.setBackground(new java.awt.Color(204, 204, 204));
        ButonAlegereCompresare.setForeground(new java.awt.Color(0, 0, 0));
        ButonAlegereCompresare.setText("Compresează");
        ButonAlegereCompresare.addActionListener(this::ButonAlegereCompresareActionPerformed);

        ButonAlegereDecompresare.setBackground(new java.awt.Color(204, 204, 204));
        ButonAlegereDecompresare.setForeground(new java.awt.Color(0, 0, 0));
        ButonAlegereDecompresare.setText("Decompreseaza");
        ButonAlegereDecompresare.addActionListener(this::ButonAlegereDecompresareActionPerformed);

        LabelTitlu.setBackground(new java.awt.Color(153, 153, 255));
        LabelTitlu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LabelTitlu.setForeground(new java.awt.Color(0, 0, 0));
        LabelTitlu.setText("Compresor de fișiere");
        LabelTitlu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelMeniuPrincipalLayout = new javax.swing.GroupLayout(PanelMeniuPrincipal);
        PanelMeniuPrincipal.setLayout(PanelMeniuPrincipalLayout);
        PanelMeniuPrincipalLayout.setHorizontalGroup(
            PanelMeniuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMeniuPrincipalLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(PanelMeniuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelMeniuPrincipalLayout.createSequentialGroup()
                        .addComponent(ButonAlegereCompresare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButonAlegereDecompresare))
                    .addComponent(LabelTitlu))
                .addGap(27, 27, 27))
        );
        PanelMeniuPrincipalLayout.setVerticalGroup(
            PanelMeniuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMeniuPrincipalLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(LabelTitlu, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(PanelMeniuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButonAlegereCompresare)
                    .addComponent(ButonAlegereDecompresare))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMeniuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMeniuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ButonAlegereCompresareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonAlegereCompresareActionPerformed
        cardLayout.show(ContainerPrincipal, "compresare");
    }//GEN-LAST:event_ButonAlegereCompresareActionPerformed

    private void ButonAlegereDecompresareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonAlegereDecompresareActionPerformed
        cardLayout.show(ContainerPrincipal,"decompresare");
    }//GEN-LAST:event_ButonAlegereDecompresareActionPerformed

    private void ButonInapoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonInapoi1ActionPerformed
        cardLayout.show(ContainerPrincipal, "meniu");
    }//GEN-LAST:event_ButonInapoi1ActionPerformed

    private void ButonInapoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonInapoi2ActionPerformed
        cardLayout.show(ContainerPrincipal, "meniu");
    }//GEN-LAST:event_ButonInapoi2ActionPerformed

    private void ButonAnulareSelectareFisiere1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonAnulareSelectareFisiere1ActionPerformed
        fisiereSelectate.clear();
        ListaFisiereCompresare.setModel(new javax.swing.DefaultListModel<>());
    }//GEN-LAST:event_ButonAnulareSelectareFisiere1ActionPerformed

    private void ButonAlegeFisiereCompresareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonAlegeFisiereCompresareActionPerformed
        fisiereSelectate.clear();
        ListaFisiereCompresare.setModel(new javax.swing.DefaultListModel<>());
        
        // în chooser salvez fișierele
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        int result = chooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                for (File f : chooser.getSelectedFiles()) {
                    fisiereSelectate.add(f);
                    ((javax.swing.DefaultListModel<String>) ListaFisiereCompresare.getModel()).addElement(f.getAbsolutePath());
                }
            }
    }//GEN-LAST:event_ButonAlegeFisiereCompresareActionPerformed

    private void ButonCompresareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonCompresareActionPerformed
        if (fisiereSelectate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Nu ai selectat niciun fisier!", 
                "Eroare", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // aleg folderul de iesire
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setDialogTitle("Alege folderul de iesire");

        int rezultat = folderChooser.showOpenDialog(this);
        if (rezultat != JFileChooser.APPROVE_OPTION) return;

        String folderIesire = folderChooser.getSelectedFile().getAbsolutePath() + "/";        
        String executabil = gasesteExecutabil("CompresorHuffman.exe", "CompresorHuffman");

        if (executabil == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Executabilul nu a fost găsit!",
                "Eroare",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            for (File f : fisiereSelectate) { // parcurg toate fișierele
                ProcessBuilder pb = new ProcessBuilder( // și le compresez
                    executabil,
                    f.getAbsolutePath(),
                    folderIesire
                );
                
                pb.redirectErrorStream(true);
                Process p = pb.start();
                String output = new String(p.getInputStream().readAllBytes());
                p.waitFor();
                //pentru debugging
                System.out.println("Output: " + output);
                System.out.println("Executabil: " + executabil);
                System.out.println("Fisier: " + f.getAbsolutePath());
                System.out.println("Folder iesire: " + folderIesire);            
                
                
                p.waitFor(); // aștept să termine
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                "Compresarea s-a terminat!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButonCompresareActionPerformed

    private void ButonAlegeFisiereDecompresareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonAlegeFisiereDecompresareActionPerformed
        fisiereSelectate.clear();
        ListaFisiereDecompresare.setModel(new javax.swing.DefaultListModel<>());
        
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        
        // aleg numai fișiere .huff pentru decompresare
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Fisiere Huffman (*.huff)", "huff"));

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            for (File f : chooser.getSelectedFiles()) {
                fisiereSelectate.add(f);
                ((javax.swing.DefaultListModel<String>) ListaFisiereDecompresare.getModel()).addElement(f.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_ButonAlegeFisiereDecompresareActionPerformed

    private void ButonAnulareSelectareFisiere2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonAnulareSelectareFisiere2ActionPerformed
        fisiereSelectate.clear();
        ListaFisiereDecompresare.setModel(new javax.swing.DefaultListModel<>());
    }//GEN-LAST:event_ButonAnulareSelectareFisiere2ActionPerformed

    private void ButonDecompresareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButonDecompresareActionPerformed
        if (fisiereSelectate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Nu ai selectat niciun fisier!", 
                "Eroare", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // aleg folderul de iesire
        JFileChooser folderChooser = new JFileChooser();
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setDialogTitle("Alege folderul de iesire");

        int rezultat = folderChooser.showOpenDialog(this);
        if (rezultat != JFileChooser.APPROVE_OPTION) return;

        String folderIesire = folderChooser.getSelectedFile().getAbsolutePath() + "/";        
        String executabil = gasesteExecutabil("DecompresorHuffman.exe", "DecompresorHuffman");

        if (executabil == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Executabilul nu a fost găsit!",
                "Eroare",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            for (File f : fisiereSelectate) {
                // extrag numele fisierului fara .huff
                String numeFisier = f.getName(); // de exemplu Frankenstein.html.huff
                String numeOriginal = numeFisier.endsWith(".huff") 
                    ? numeFisier.substring(0, numeFisier.length() - 5) 
                    : numeFisier; // acuma va fi Frankenstein.html

                // adaug _decompresat inainte de extensie
                int ultimPunct = numeOriginal.lastIndexOf('.');
                String numeIesire = (ultimPunct != -1)
                    ? numeOriginal.substring(0, ultimPunct) + "_decompresat" + numeOriginal.substring(ultimPunct)
                    : numeOriginal + "_decompresat"; // acuma va fi Frankenstein_decompresat.html

                ProcessBuilder pb = new ProcessBuilder(
                    executabil,
                    f.getAbsolutePath(),  // fisier.huff
                    folderIesire,         // folderul de iesire
                    numeIesire            // numele fisierului de iesire
                );

                pb.redirectErrorStream(true);
                Process p = pb.start();
                String output = new String(p.getInputStream().readAllBytes());
                p.waitFor();
                System.out.println("Output: " + output);
            }

            javax.swing.JOptionPane.showMessageDialog(this,
                "Decompresarea s-a terminat!");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButonDecompresareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MeniuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButonAlegeFisiereCompresare;
    private javax.swing.JButton ButonAlegeFisiereDecompresare;
    private javax.swing.JButton ButonAlegereCompresare;
    private javax.swing.JButton ButonAlegereDecompresare;
    private javax.swing.JButton ButonAnulareSelectareFisiere1;
    private javax.swing.JButton ButonAnulareSelectareFisiere2;
    private javax.swing.JButton ButonCompresare;
    private javax.swing.JButton ButonCompresie;
    private javax.swing.JButton ButonDecompresare;
    private javax.swing.JButton ButonDecompresie;
    private javax.swing.JButton ButonInapoi1;
    private javax.swing.JButton ButonInapoi2;
    private javax.swing.JLabel LabelAlegereCompresare;
    private javax.swing.JLabel LabelAlegereDecompresare;
    private javax.swing.JLabel LabelTitlu;
    private javax.swing.JList<String> ListaFisiereCompresare;
    private javax.swing.JList<String> ListaFisiereDecompresare;
    private javax.swing.JPanel PanelCompresare;
    private javax.swing.JPanel PanelDecompresare;
    private javax.swing.JPanel PanelMeniuPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
