name: Build Complete App Package

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Compresor (Linux)
        run: |
          cd Compresor_Huffman
          cmake .
          make
          mv Compresor_Huffman ../CompresorHuffman_linux

      - name: Build Decompresor (Linux)
        run: |
          cd Decompresor_Huffman
          cmake .
          make
          mv Decompresor_Huffman ../DecompresorHuffman_linux

      - name: Pregatesc pachetul Linux
        run: |
          mkdir -p Java_App_Linux/executabile
          cp Java_App/Huffman_Compiler.jar Java_App_Linux/
          cp CompresorHuffman_linux Java_App_Linux/executabile/CompresorHuffman_linux
          cp DecompresorHuffman_linux Java_App_Linux/executabile/DecompresorHuffman_linux

      - name: Upload Linux package
        uses: actions/upload-artifact@v4
        with:
          name: Java_App_Linux
          path: Java_App_Linux/

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Compresor (Mac)
        run: |
          cd Compresor_Huffman
          cmake .
          make
          mv Compresor_Huffman ../CompresorHuffman_mac

      - name: Build Decompresor (Mac)
        run: |
          cd Decompresor_Huffman
          cmake .
          make
          mv Decompresor_Huffman ../DecompresorHuffman_mac

      - name: Pregatesc pachetul Mac
        run: |
          mkdir -p Java_App_Mac/executabile
          cp Java_App/Huffman_Compiler.jar Java_App_Mac/
          cp CompresorHuffman_mac Java_App_Mac/executabile/CompresorHuffman_mac
          cp DecompresorHuffman_mac Java_App_Mac/executabile/DecompresorHuffman_mac

      - name: Upload Mac package
        uses: actions/upload-artifact@v4
        with:
          name: Java_App_Mac
          path: Java_App_Mac/